version: '3'

services:
  app:
    restart: always
    build: .
    ports:
      - "8001:8001"
    env_file: "./envs/dev-docker.env"
    networks:
      - traefik-internal

networks:
  traefik-internal:
    external: true
